### ISSUE TITLE
SW: Logfile name always DATA.LOG

### ISSUE THREAD

**Issue by ppannuto** [lab11/socitrack#18]
Since we're defaulting to `DISABLE_RTC_TIME_CHECK`, the logger doesn't try to use time at all, and will name the logfile `DATA.LOG` even if the device does have a valid timestamp.

**Comment by hedgecrw** [comment]
This is fixed with the latest check-in. Now it works like so:

If the RTC time is valid at boot, it will automatically create the time-based log file. If it is not valid, it will create a file named ID@DATA.LOG. In the future, once a valid RTC time is acquired by the network, a new log file will be created with the correct time-based name.
